---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/bansala1/fcpams.bansalancoop.com
    - /bin/cp -R admin $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R citizen $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R includes $DEPLOYPATH
    - /bin/cp -R staff $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp login.php $DEPLOYPATH
    - /bin/cp logout.php $DEPLOYPATH
    - /bin/cp register.php $DEPLOYPATH
    - /bin/cp migrate_is_ho.php $DEPLOYPATH
    - /bin/cp trigger_alarm.php $DEPLOYPATH
    - /bin/cp update_location.php $DEPLOYPATH
    - /bin/cp get_active_devices.php $DEPLOYPATH
    - /bin/cp live_map.php $DEPLOYPATH
